package com.example.appfetin.ui.theme

import androidx.compose.ui.graphics.Color

val LightBackground = Color(0xFFFFFFFF)
val LightForeground = Color(0xFF09090B)
val LightCard = Color(0xFFFFFFFF)
val LightCardForeground = Color(0xFF09090B)
val LightPopover = Color(0xFFFFFFFF)
val LightPopoverForeground = Color(0xFF09090B)
val LightPrimary = Color(0xFF2F30A4)
val LightPrimaryForeground = Color(0xFFFAFAFA)
val LightSecondary = Color(0xFFF4F4F5)
val LightSecondaryForeground = Color(0xFF27272A)
val LightMuted = Color(0xFFF4F4F5)
val LightMutedForeground = Color(0xFF6F6F7B)
val LightAccent = Color(0xFFF4F4F5)
val LightAccentForeground = Color(0xFF27272A)
val LightDestructive = Color(0xFFEF4444)
val LightBorder = Color(0xFFE4E4E7)
val LightInput = Color(0xFFE4E4E7)
val LightRing = Color(0xFFA1A1AA)

val DarkBackground = Color(0xFF09090B)
val DarkForeground = Color(0xFFFAFAFA)
val DarkCard = Color(0xFF27272A)
val DarkCardForeground = Color(0xFFFAFAFA)
val DarkPopover = Color(0xFF27272A)
val DarkPopoverForeground = Color(0xFFFAFAFA)
val DarkPrimary = Color(0xFFE4E4E7)
val DarkPrimaryForeground = Color(0xFF27272A)
val DarkSecondary = Color(0xFF3F3F46)
val DarkSecondaryForeground = Color(0xFFFAFAFA)
val DarkMuted = Color(0xFF3F3F46)
val DarkMutedForeground = Color(0xFFA1A1AA)
val DarkAccent = Color(0xFF3F3F46)
val DarkAccentForeground = Color(0xFFFAFAFA)
val DarkDestructive = Color(0xFFB91C1C)
val DarkBorder = Color(0xFF3F3F46)
val DarkInput = Color(0xFF3F3F46)
val DarkRing = Color(0xFF82828D)